
remote_theme: "ankit-kumar-jat/limp-dark" # "flancast90/millidocs-dark"
plugins:
- jekyll-remote-theme

title: SIGNL4 Technical Documentation
description: A set of technical documentations about SIGNL4.
url: "https://signl4.github.io/docs/integrations"
