
remote_theme: "just-the-docs/just-the-docs"
# Find the documentation here: https://just-the-docs.com/docs/customization/
# With side bar and dark: "vaibhavvikas/jekyll-theme-minimalistic"
# Nice and light: "pages-themes/slate"
# Dark "flancast90/millidocs-dark"
plugins:
- jekyll-remote-theme

color_scheme: dark

aux_links:
  "View on GitHub":
    - "https://github.com/signl4/docs"

title: SIGNL4 Docs
description: A set of technical documentations about SIGNL4.
url: "https://signl4.github.io/docs/integrations"
