
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# With side bar and dark: "vaibhavvikas/jekyll-theme-minimalistic"
# Nice and light: "pages-themes/slate"
# Dark "flancast90/millidocs-dark"
plugins:
- jekyll-remote-theme

title: SIGNL4 Technical Documentation
description: A set of technical documentations about SIGNL4.
url: "https://signl4.github.io/docs/integrations"
