
title: SIGNL4 Technical Documentation
description: A set of technical documentations about SIGNL4.

theme: jekyll-theme-chirpy

# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme
# color-scheme: "dark"
