
title: SIGNL4 Technical Documentation
description: A set of technical documentations about SIGNL4.

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme

# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme
# color-scheme: "dark"
